CREATE TABLE sales_data (
	serial_number SERIAL PRIMARY KEY,
	product_name VARCHAR (100), 
	region VARCHAR (100), 
	sales_date DATE, 
	units_sold SMALLINT, 
	revenue DECIMAL
);

INSERT INTO sales_data (product_name, region, sales_date, units_sold, revenue)
VALUES 
('Organic Apples', 'North', '2022-01-01', 100, 2000.00),
('Organic Bananas', 'North', '2022-01-01', 150, 3000.00),
('Organic Apples', 'South', '2022-01-01', 50, 1000.00),
('Organic Bananas', 'South', '2022-01-01', 200, 4000.00),
('Organic Apples', 'North', '2022-02-01', 75, 1500.00),
('Organic Bananas', 'North', '2022-02-01', 125, 2500.00),
('Organic Apples', 'South', '2022-02-01', 25, 500.00),
('Organic Bananas', 'South', '2022-02-01', 175, 3500.00);

SELECT *
FROM sales_data;

-- Task 3: Find the total revenue generated by the company.
SELECT SUM(revenue) as total_revenue
FROM sales_data;

-- Task 3.1: Find the total revenue generated by the company per product
SELECT region, product_name, SUM(revenue) as total_revenue
FROM sales_data
GROUP BY region, product_name;


-- Task 4: Find the total number of units sold.
SELECT region, product_name, 
		SUM(units_sold) as total_units_sold,
		SUM(revenue) as total_revenue
FROM sales_data
GROUP BY region, product_name;

-- Task 5: Find the total revenue generated by product.
SELECT product_name, 
		SUM(units_sold) as total_units_sold,
		SUM(revenue) as total_revenue
FROM sales_data
GROUP BY product_name;